languageCode = "en-us"
title = "Massively"
baseURL = "http://localhost:1313/"
theme = "../.."

[params.posts]
    foldername = "post"

[params.settings]
    googleanalytics = "UA-113904582-3"
    disqus = "hugo-massively"