name: CI/CD

on:
    push:
        branches: 
            - dev

jobs:
deploy:
  name: Deploy to Netlify
  needs: build
  runs-on:  ubuntu-18.04
  steps:
    - name: Download public directory
      uses: actions/download-artifact@v2
      with:
        name: public
        path: public/
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy -p --dir=public
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}